### ISSUE TITLE
Improve code generation with text/template

### ISSUE THREAD

**Issue by Jragonmiris** [go-gl/mathgl#32]
Issues #30 and #29 are basically on hold because of some of the difficulty in rewriting the code generation. I think it would just plain be easier to rewrite the incredibly ad-hoc, ugly code gen script with text/template.

The new version likely would no longer use the Makefile, and instead directly generate the `float64` version due to text/template's greater flexibility.

**Comment by shurcooL** [comment]
Yes, `go generate` is just a standard way for Go packages to run some commands to update their source code.

It's nice because it's a standard that's easy to follow and makes contributing to various Go packages easier. You know it's always `go generate`, rather than `make` or `make.sh` or something else custom and non-standard.

See here for an example of replacing a bash file with `go generate` directives: https://github.com/gopherjs/websocket/commit/c80adc16bea6faaf1a252b91c8facc50e5bba75b.

**Comment by alexvasi** [comment]
I tried to rewrite genprog using `text/template`. Only vectors for now. Here is the result:
https://github.com/alexvasi/mathgl/commit/1ed7256c21b6f9c4c7aa189ad7526dd54275dd4c

The main idea was to place all crucial information directly in the template and not in the program that generates code. I know, I could have passed meta info about types and functions to template. Or I could have used sub-templates for each function for example. In the end I decided against it. Template almost looks like a go code, if you squint hard enough. And that's a good thing, I guess. Except maybe there will be `float32/64` flag later.

First of all it works. It is a zero-diff change... well, not actually. The order of functions in `vector.go` is different now. It takes 10 or so additional lines in template to make the order the same. I dumped them. But that's how I tested new generator.

Here is some caveats:
* `text/template` is sloppy with whitespaces. I abused `gofmt` and it's called after template rendering.
* I changed template separators from `{{` to `<<`. It is too many curly brackets in go code already.
* The readability of `vector.tpl` is not perfect.
* Broken diff. It is hard to validate new generator with changed functions order. I should add some tests for each vector function to `vec_test.go` anyway.
