### ISSUE TITLE
Go modules-compatible version tags

### ISSUE THREAD

**Issue by jclc** [go-gl/mathgl#73]
With Go modules now out, version tags should be in the form vX.Y.Z . If the API is stable, there should be a v1.0.0 tag.

**Comment by Zyl9393** [comment]
There currently is a tag `Go1.2.2`. Just to be safe, maybe go to `v1.3.0` next?

**Comment by jclc** [comment]
The Go mod command ignores tags that don't begin with 'v', so any old tags in this repository shouldn't matter.

**Comment by pwaller** [comment]
Is the API considered stable? If so, we should go with a `1.x` tag. If not, we should start at `0.x`. Are there any known reasons to break the API? I'm guessing not, based on the slow rate of change over the last few years.

If my speculation is right, I don't see why the first tag couldn't be v1.0.0. Ping @Zaerei for opinion.

**Comment by Zaerei** [comment]
Yeah, it's mostly not stable out of paranoia. I think the reason I never stabilized is the variable-sized matrices which I never really decided on whether they're worth adding. There's a lot of documentation warning you about it but you probably shouldn't use them. Still, at this point removing them would be breaking and we're pseudo-stable in the sense that it's been so long since a major breaking change every user has a reasonable expectation of non-breakage.

**Comment by jclc** [comment]
If they're not worth keeping and there's another library that does the same thing better, wouldn't v1.0.0 be the perfect time to remove it?

**Comment by Zyl9393** [comment]
Note that semver major versions >0 only require stability of the interface, not reliability or correctness of the underlying code. If you don't plan on making changes to the interface, you should tag it as `v1.0.0`. There'll almost always be unknown issues anyway. I understand that you want to hold this library to a higher standard since it really just implements established knowledges, but then again it isn't exempt from the fallacies of software development, just because it's a math library.

**Comment by Zaerei** [comment]
To be clear, the issue isn't bugs, it's that we've essentially been feature complete (barring adding things for requests) for so long I kind of feel bad removing some things like the matrix stack or variable sized matrices. We've been kind of "soft-1.0" essentially. There's also an issue we never addressed about passing by pointer vs value, though I suppose we could add the pointer-based code at a later time and give the user a choice.

I'll probably just end up doing a 1.0 tag, but it won't happen for a few days.

**Comment by Kintar** [comment]
It's been over a year now, and this issue hasn't been resolved.  Is there a good reason there's no v1.0.0 tag yet?  I'd love to be able to specify semver in my go.mod files instead of looking at the ugly `github.com/go-gl/mathgl v0.0.0-20190713194549-592312d8590a` that's currently produced.

**Comment by jclc** [comment]
Well the repo hasn't been updated in over a year now, it's about as stable as it gets. The only major future change I can think of will be generics support when that's added to Go and that could warrant a v2 tag.

**Comment by pwaller** [comment]
Thanks for pinging the thread @jclc. I've made a tag on the basis that I don't see anyone suggesting we want to do breaking changes any time soon.

https://github.com/go-gl/mathgl/releases/tag/v1.0.0
