### ISSUE TITLE
Performance of basic vector math operations could be up to a 100 times faster.

### ISSUE THREAD

**Issue by EliasCK** [go-gl/mathgl#85]
Here's a quick benchmark:
```

package game

import (
	"testing"
	"math"
)

type CustomVec3 struct {
	x float32
	y float32
	z float32
}

func Benchmark_TestVec3(b *testing.B) {
	var customVecs = make([]CustomVec3, 300000)
	var goVecs = make([]Vec3, 300000)

	b.Run("Vec3 Normalize", func(b *testing.B) {
    for j := 0; j < b.N; j++ {
			for i := 0; i < len(goVecs); i++ {
				p := goVecs[i]
				p[0] = 1
				p[1] = 1
				p2 := p
				len := float32(math.Sqrt(float64(p2[0] * p2[0] + p2[1] * p2[1] + p2[2] * p2[2])))
				mul := 1.0 / len
				p2[0] = p2[0] * mul
				p2[1] = p2[1] * mul
				p2[2] = p2[2] * mul
			}
		}
	})

	b.Run("CustomVec3 Normalize", func(b *testing.B) {
    for j := 0; j < b.N; j++ {
			for i := 0; i < len(customVecs); i++ {
				p := customVecs[i]
				p.x = 1
				p.y = 1
				p2 := p
				len := float32(math.Sqrt(float64(p2.x * p2.x + p2.y * p2.y + p2.z * p2.z)))
				mul := 1.0 / len
				p2.x = p2.x * mul
				p2.y = p2.y * mul
				p2.z = p2.z * mul
			}
		}
	})
}

```

Result:
![image](https://user-images.githubusercontent.com/11874914/74741023-5a14c180-525c-11ea-9028-63851b18e98d.png)

It would also be SO nice to just write v.x, v.y, v.z and so on... Don't know what arguments there is really for using [3]float3 as a data structure. I'm assuming it's bounds checking that makes everything so slow?

**Comment by pwaller** [comment]
Try doing:

```
go test -c
```

To compile your example. Then do `go tool objdump -s TestVec3 <test binary>` (test binary probably called game.test), and look at the three disassembled functions. You'll notice that CustomVec3 is much shorter - it has been optimized away and is doing no floating point operations at all, where as Vec3 is not optimized away. So I think you've tickled a funny difference in the compiler's handling of values.

The compiler can do this because you don't actually use the result at any point. You compute p2, but there is no observable effect of doing so, and so the compiler is free to avoid computing it in the first place.

If you instead modify the arrays in place, by taking the address with `&goVecs[i]` and `&customVecs[i]` this modifies the array in place. It is still the case that there are no observable effects from the computation, but it is beyond the bounds of the optimizer to figure that out, so both functions then do the full work. (And they avoid a bit of copying). In that case, both functions run at more or less the same rate for me.

Another way you can get a sense that the "faster" benchmark result is unrealistic is to count up the total number of floating point operations which happen in the elapsed time. For your optimized case with ballpark math I get a value like ~20 billion per second, would be on the "surprisingly high" end, given that you've got a square-root in there, and given that the CPU can do something like that many integer-ops per second.

One further thought: it's also nothing to do with bounds checking, because the size of the array `[3]float32` is known at compile time, so the compiler doesn't do runtime bounds checks for constantly-specified indexes there, it would just give a compile error if it were incorrectly specified.

**Comment by EliasCK** [comment]
Thanks a lot for the insight! I figured I must have been jumping to conclusions. 

It does seem that structs are faster in many many other cases. I'll look more into it tomorrow to learn more :)

I tried quickly making a simpler test - And I'm assigning the value back into the array this time, so it shouldn't be optimized away!
 
```
package game

import "testing"

type V1 struct {
	x float32
	y float32
}

type V2 [2]float32

func (a V1) Add(b V1) V1 { return V1{a.x + b.x, a.y + b.y} }
func (a V2) Add(b V2) V2 { return V2{a[0] + b[0], a[1] + b[1]} }

func Benchmark_TestVec3(b *testing.B) {
	var v1s = make([]V1, 300000)
	b.Run("V1 (Struct)", func(b *testing.B) {
                for j := 0; j < b.N; j++ {
			for i := 0; i < len(v1s); i++ {
				p := v1s[i]
				p.x = 1
				p.y = 1
				p = p.Add(p.Add(p))
				v1s[i] = p
			}
		}
	})

	var v2s = make([]V2, 300000)
	b.Run("V2 (Array)", func(b *testing.B) {
                for j := 0; j < b.N; j++ {
			for i := 0; i < len(v2s); i++ {
				p := v2s[i]
				p[0] = 1
				p[1] = 1
				p = p.Add(p.Add(p))
				v2s[i] = p
			}
		}
	})
}
```

![image](https://user-images.githubusercontent.com/11874914/74786236-7c363000-52ac-11ea-8dab-9eec8de85135.png)

**Comment by pwaller** [comment]
Interesting.

Again you've tickled the optimizer, and it's not doing the add, but it has inlined p.Add and constant-propagated it. Take a look at the disassembly and look at the size difference between the functions. In the struct case there 

To defeat the optimizer in this case you can take v1s and v2s and make them global public variables `V1s` and `V2s`. Then again they perform the same.

Another interesting tool you can use is `GOCACHE=$PWD/func1 GOSSAFUNC=Benchmark_TestVec3.func1 go test -c` and `GOCACHE=$PWD/func2 GOSSAFUNC=Benchmark_TestVec3.func2 go test -c`. This emits a HTML file ssa.html which shows the code after various stages in the compiler. For the struct case, the optimizer has reduced the add to a constant value during the `opt` stage. You can click on individual variables to highlight them and see how they are propagated through the compiler.

Unfortunately this microbenchmark isn't reflective of something you'd see in a typical application where you're not adding together constants. Avoiding this kind of pitfall is difficult in benchmarks. I'm afraid I can't give a general rule for doing so.

**Comment by purelazy** [comment]
Curious.

My 2 cents. If structs are faster, then I'm all for structs. .x, .y  and .z are easier to type. It not as if we "index over" the coordinates that often. I started using arrays, and after reading this changed to structs. What happening, why is this still open? Is there a debate behind the scenes?

**Comment by EliasCK** [comment]
To me, this just looks like the compiler just has a much easier time optimizing structs. So my take away is, that if there are any optimizations the compiler can do, that there's a better chance it'll do it if you use structs. That's a good enough reason to go with structs IMO, but would also love to do a better test at some point, and take a real application that produces an image, with real averagely written vector code, without optimization in mind. And see if there are any benefits to be had in a typical application.

**Comment by purelazy** [comment]
EliasCK - the struct and array are accessed in pretty much the same way - logically speaking. So on syntax-aethetic ground I would go for .x vs [0]. Less typing + more meaning.

**Comment by pwaller** [comment]
@purelazy 

> My 2 cents. If structs are faster, then I'm all for  [paraphrase] .. doing something.

I don't yet see presented evidence structs are faster. Please see my rationale below. My opinion on that could change with more realistic data.

However, my opinion on whether go-gl/mathgl should change something is that it should not if it is a public API breaking change, because at that point you've essentially made a new package, and broken all consumers of go-gl/mathgl. So unless there is a significant, pressing, compelling reason to change, it should not. If someone wants to start a new library with a different name, with a different approach, nothing is stopping them. I would even offer space in the github.com/go-gl/... namespace for such a package if it was compelling enough and anyone thought it mattered to do so.

> What's happening? Why is this issue still open? Is there a debate behind the scenes?

Context:

1. I'm a maintainer under go-gl, and volunteering odd bits of my time to try and keep the go-gl repositories tidy. So I'll respond to the odd issue, time and energy permitting.
2. I have not contributed much to mathgl specifically, and I didn't write any of the code (that I recall).
3. I don't know @EliasCK. I assume they filed this issue because they discovered some surprising performance behaviour whilst hacking on something. They probably wondered why mathgl chose to implement using arrays rather than structs, given that they saw more performance with structs in a case that mattered to them.
4. I replied because I had some suspicions that the benchmarks as presented were on shaky ground, so wanted to help @EliasCK understand what he was seeing in more detail.
5. I assume the primary contributor of the library, when they were designing it 5+ years ago, @Zaerei, had good reasons for choosing arrays over structs. I don't know what those design choices were exactly, but I might guess that one good reason is that it means all types have the same form: https://godoc.org/golang.org/x/image/math/f64 ([3]float64, [4]float64, [16]float64, etc). Note that the types are actually defined in an external package, which was changed in #35. I've started a discussion there to ask why we don't use our own definitions, for what it's worth.

#### On performance

My own takeaway (as it currently stands) from the experiment is that arrays and structs actually have the same performance once the code gets sufficiently complicated. It's just that @EliasCK managed to make some sufficiently simple code where the optimizer was able to remove all of the useful work for structs. Note that in this case this doesn't mean that the optimizer is better for structs, it just means that the program under test wasn't doing anything interesting with those structs.

#### On style

I don't have a horse in this race. The difference between using `p.X` and `p[0]` seems small to me. The latter can facilitate easier programmatic access since you can do `[i]`, as opposed to something like`*[]*int{&p.X, &p.Y, &p.Z}[i]`. As mentioned earlier it means the type of Vec3 is [3]float, Vec4 [4]float, and Aff3 is [6]float, etc.

If you really cared about how it was written, I think you could use unsafe.Pointer to cast your array into a struct, not that I would recommend doing this.

#### What next

In summary, I think this issue should be closed, since there isn't currently anything actionable to do for go-gl/mathgl. I don't want to suppress educational discussion though, so don't take this as a sign to stop discussing the matter. A real-world benchmark result showing a significant difference which computes something interesting (and does something with the result) would be intriguing. Likely however, it won't mean changing go-gl/mathgl unless someone could demonstrate a way to do it without breaking the API. I believe this to be impossible. So the relevance to this project is low.

I suspect that such a result might be better sent to the Go issue tracker for a fix in the compiler to make the two approaches perform the same. They are likely to have the same concerns about the benchmark representing realistic work though, which the most recent example does not seem to be for me, since it involves taking the constant vector {1,1} and adding it to itself many times. More interesting would be if you could demonstrate a performance difference for non-constants.

**Comment by pwaller** [comment]
Also:
> Is there a debate behind the scenes?
No, it's all in this issue.

**Comment by Zaerei** [comment]
Just to chime in, a very good reason I chose the array is due to some Go spec guarantees. I don't know if it's changed in the intervening decade, but **at the time**, Go _did not_ guarantee struct layout memory order, nor packing behavior, in the spec. Conversely, arrays (and the arrays that back slices) are spec-guaranteed to be in memory-aligned order of the elements.

While it's incredibly _unlikely_ that the compiler would every reorder elements in a struct, or pack them, I wanted to eliminate any potential for that nightmare since the intent was for types from the package to be in principle able to be fed directly into opengl shaders via go-gl. This desire was strong enough that matrices themselves are handled in CMO, like in open gl/GLSL, despite most languages, including Go itself, using RMO order.  (And also provided the opportunity to confidently use handwritten asm if desired, which we ended up not doing ultimately). There's even a (still open) issue on the main Go repo about updating the spec to guarantee struct behavior IIRC, that I posted in for this reason.

In particular, clever compiler optimizations were something that would ideally be avoided. While, again, extremely unlikely, I wanted to avoid the compiler "helping" and omitting say, the second element of a Vec3 because it never observed it being used in the entire program.

There were little choices that informed this as well, specifically that since GLM (what this package is based on) can use compiler magic to do the operators, and is based on glsl's canonical names, I couldn't choose a default. Vectors are automatically both xyzw, and rgba, and I think rstu. I think some earlier draft actually had all the swizzles as member functions, but ended up deciding it was too bloated to really belong. 

Finally, it was simply easier to write some of the templated codegen based on array indices rather than having to do a lookup for the struct characters every time (especially since this was written well before `go gen` existed). I'm not sure in the long term to `f64` package was really needed, but I wanted to future proof in case GPU technology started moving in a more double-heavy direction or people had special needs.

Truth told, the very first draft, to my recollection, was indeed with structs, but I chose arrays for what I believe are reasons that were very good at the time. And, as noted, this package is basically in LTS mode at this point and switching entirely would be irresponsible. You're welcome to use the `X`, `Y,` and `Z` functions, and I desperately hope Go's compiler is at least smart enough to inline those.
