### ISSUE TITLE
`mgl64.Round(0, 2)` returns `-0`

### ISSUE THREAD

**Issue by Prim69** [go-gl/mathgl#86]
![image](https://user-images.githubusercontent.com/13991048/167282334-49a12ecd-376b-48d2-927c-fe6dec41d954.png)
![image](https://user-images.githubusercontent.com/13991048/167282336-d7800851-1e24-4f00-829c-cad43c4d6e6d.png)
im not sure how this is even possible lmao

**Comment by pwaller** [comment]
Nice find. Signed zero is a thing that floating point numbers have :) 

https://en.wikipedia.org/wiki/Signed_zero

It looks like this is arising from the current definition of `Round`, which at a glance is doing 'tie breaks round towards nearest', with 'rounding towards zero'.

https://github.com/go-gl/mathgl/blob/592312d8590acb0686c14740dcf60e2f32d9c618/mgl64/util.go#L137-L146

The `if t > 0` is false, so it's rounding as if 'zero is negative'. The sign is appearing from `math.Ceil(-0.5)`: https://go.dev/play/p/RtDbZu9JNlF

I think the fix is to change the condition to `if t >= 0` because negative zero was neglected. Patches welcome? :)
